Feature:送信ボタンの連打防止とslackチャンネルの変更
glucoseinc/transcribe-ui pull request #9
Opened 2021-04-30 04:48 UTC by ryo0511

- ファイルをアップロードする時の送信ボタンが何度もクリックできてしまい、S3に同じファイルをアップロードできてしまっていたため、それを防止するよう変更した
- 文字起こしの終了を通知するslackチャンネルを`pjt_dev_support`に変更した

2021-04-30 05:00 UTC, shnjp requested changes

2021-04-30 05:00 UTC, shnjp commented on lambda/trigger-S3/notifycate/slack.py
> +    post_DM(pjt_dev_support, message)
post_DMとなっているけど対象はチャンネルではないのでしょうか？

2021-04-30 05:00 UTC, shnjp commented on src/fileUpLoad.tsx
> +  clicked: boolean
まず、「resetボタンを押さないと再びアップロードできない」という仕様はユーザーは絶対わからないので諦めよう。
防ぎたい挙動は、
* Upload中に連打できないようにする。（ユーザーがアップロード中だということがわかる）
* 同じファイルを再度アップロードできないようにする
の2点だよね。

前者はアップロード中にボタンをdisabledにする & Upload中であるという文言をだす
後者はアップロードが完了したらinputをクリアする
これで実現できませんか？

2021-04-30 07:34 UTC, ryo0511 commented on lambda/trigger-S3/notifycate/slack.py
> +    post_DM(pjt_dev_support, message)
確かにそうですね
`postDM`と`post_message`の違いもあまりなさそうなので`post_message`に統合しようと思います

2021-04-30 07:37 UTC, ryo0511 commented on src/fileUpLoad.tsx
> +  clicked: boolean
> 「resetボタンを押さないと再びアップロードできない」という仕様はユーザーは絶対わからない

ユーザーの理解度を考えていませんでした

> 前者はアップロード中にボタンをdisabledにする & Upload中であるという文言をだす
後者はアップロードが完了したらinputをクリアする
これで実現できませんか？

できると思います。やってみます。

2021-04-30 10:18 UTC, shnjp requested changes
isDisable, isUploaded を `state` みたいなものにまとめればよいのではと思います

2021-04-30 10:18 UTC, shnjp commented on src/fileUpLoad.tsx
> +          {this.state.isUploaded
終了メッセージを出すのはとても良いのだけど、
僕が言ったのは、「アップロード中もメッセージを出すべきでは？」ということです

2021-04-30 10:18 UTC, shnjp commented on src/fileUpLoad.tsx
> +  isDisable: boolean
ボタンがdisabledかどうかは、upload中かどうか、などの結果なので、フォーム自体がdisabledかどうかを持つのは違和感があります。

それはそれとして時制がずれてんのもきになる。

2021-04-30 10:37 UTC, ryo0511 commented on src/fileUpLoad.tsx
> +          {this.state.isUploaded
```
<input
   type="submit"
    value={this.state.isDisable ? 'アップロード中' : 'アップロード'}
   disabled={this.state.isDisable}
 />
```
ここでアップロード中は送信ボタンの文言を変えてみたのですがもっとわかりやすくした方がいいでしょうか？

2021-04-30 10:43 UTC, ryo0511 commented on src/fileUpLoad.tsx
> +  isDisable: boolean
変数名の付け方がおかしいという話ですか？
それとも、実装の方法についての話でしょうか？

時制は`isUploaded `→`wasUploaded`ですね。直します。

2021-05-06 02:45 UTC, shnjp commented on src/fileUpLoad.tsx
> +          {this.state.isUploaded
あ、見通していた。それでいいと思う

2021-05-06 02:47 UTC, shnjp commented on src/fileUpLoad.tsx
> +  isDisable: boolean
is disable -> is disabled じゃないかな？　と思った。

もうコードをそのように書き始めてると思うけど、"Formとしての状態 入力中/動作中/動作完了（次の入力待ち)" があった上で、そのForm内要素個別の状態を演繹すべきだとおもうよ

2021-07-19 09:29 UTC, merged